Address review comments

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -954,13 +954,13 @@ steps:
       WORKSPACE_DIR: /tmp/push-build-darwin-amd64-fips
       TELEPORT_DIR: /tmp/push-build-darwin-amd64-fips/go/src/github.com/gravitational/teleport
       GODL_DIR: /tmp/push-build-darwin-amd64-fips/go/src/github.com/gravitational/godl
-      GODL_COMMIT: dev.boringcrypto.go1.15
+      BORINGCRYPTO_BRANCH: dev.boringcrypto.go1.15
     commands:
       - set -u
       - mkdir -p $TELEPORT_DIR $GODL_DIR
       - cd $GODL_DIR
       - git clone https://github.com/gravitational/godl.git .
-      - git checkout $GODL_COMMIT
+      - git checkout $BORINGCRYPTO_BRANCH
       - cd $TELEPORT_DIR
       - git clone https://github.com/gravitational/teleport.git .
       - git checkout ${DRONE_TAG:-$DRONE_COMMIT}
@@ -973,17 +973,22 @@ steps:
       - GIT_SSH_COMMAND='ssh -i $WORKSPACE_DIR/.ssh/id_rsa -o UserKnownHostsFile=$WORKSPACE_DIR/.ssh/known_hosts -F /dev/null' git submodule update --init e
       # this is allowed to fail because pre-4.3 Teleport versions don't use the webassets submodule
       - GIT_SSH_COMMAND='ssh -i $WORKSPACE_DIR/.ssh/id_rsa -o UserKnownHostsFile=$WORKSPACE_DIR/.ssh/known_hosts -F /dev/null' git submodule update --init --recursive webassets || true
+      # set version
+      - if [[ "${DRONE_TAG}" != "" ]]; then echo "${DRONE_TAG##v}" > $WORKSPACE_DIR/go/.version.txt; else make print-version > $WORKSPACE_DIR/go/.version.txt; fi; cat $WORKSPACE_DIR/go/.version.txt
+      - echo "$BORINGCRYPTO_BRANCH" > $WORKSPACE_DIR/go/.bc_commit.txt
+      - cat $WORKSPACE_DIR/go/.bc_commit.txt
       - rm -rf $WORKSPACE_DIR/.ssh
       - mkdir -p $WORKSPACE_DIR/go/cache
 
   - name: Build the boringcrypto Go builder
     environment:
+      WORKSPACE_DIR: /tmp/push-build-darwin-amd64-fips
       GODL_DIR: /tmp/push-build-darwin-amd64-fips/go/src/github.com/gravitational/godl
-      BORINGCRYPTO_BRANCH: dev.boringcrypto.go1.15
     commands:
-      - set -u
+      - set -exu
       - cd $GODL_DIR
       - mkdir build
+      - export BORINGCRYPTO_BRANCH=$(cat $WORKSPACE_DIR/go/.bc_commit.txt)
       - go build -o $GODL_DIR/build/$BORINGCRYPTO_BRANCH $BORINGCRYPTO_BRANCH/main.go
 
   - name: Pull boringcrypto build tarball from S3
@@ -1010,7 +1015,7 @@ steps:
       GOPATH: /tmp/push-build-darwin-amd64-fips/go
       GOCACHE: /tmp/push-build-darwin-amd64-fips/go/cache
       # use custom Go compiler
-      GO_BINARY: /tmp/push-build-darwin-amd64-fips/go/src/github.com/gravitational/godl/build/dev.boringcrypto.go1.15
+      GODL_DIR: /tmp/push-build-darwin-amd64-fips/go/src/github.com/gravitational/godl
       OS: darwin
       ARCH: amd64
       WORKSPACE_DIR: /tmp/push-build-darwin-amd64-fips
@@ -1018,7 +1023,9 @@ steps:
     commands:
       - set -u
       - cd $WORKSPACE_DIR/go/src/github.com/gravitational/teleport
-      - make clean release OS=$OS ARCH=$ARCH FIPS=$FIPS GO_BINARY=$GO_BINARY
+      - export VERSION=$(cat $WORKSPACE_DIR/go/.version.txt)
+      - export BORINGCRYPTO_BRANCH=$(cat $WORKSPACE_DIR/go/.bc_commit.txt)
+      - make -C e clean release GITTAG=v$VERSION VERSION=$VERSION OS=$OS ARCH=$ARCH FIPS=$FIPS GO_BINARY="$GODL_DIR/build/$BORINGCRYPTO_BRANCH"
 
   - name: Clean up exec runner storage (post)
     environment:
@@ -1037,7 +1044,7 @@ steps:
         export DRONE_BUILD_LINK="${DRONE_SYSTEM_PROTO}://${DRONE_SYSTEM_HOSTNAME}/${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}/${DRONE_BUILD_NUMBER}"
         export GOOS=$(go env GOOS)
         export GOARCH=$(go env GOARCH)
-        curl -sL -X POST -H 'Content-type: application/json' --data "{\"text\":\"Warning: \`$GOOS-$GOARCH\` artifact build failed for [\`${DRONE_REPO_NAME}\`] - please investigate immediately!\nBranch: \`${DRONE_BRANCH}\`\nCommit: \`${DRONE_COMMIT_SHA}\`\nLink: $DRONE_BUILD_LINK\"}" $SLACK_WEBHOOK
+        curl -sL -X POST -H 'Content-type: application/json' --data "{\"text\":\"Warning: \`$GOOS-$GOARCH\` FIPS artifact build failed for [\`${DRONE_REPO_NAME}\`] - please investigate immediately!\nBranch: \`${DRONE_BRANCH}\`\nCommit: \`${DRONE_COMMIT_SHA}\`\nLink: $DRONE_BUILD_LINK\"}" $SLACK_WEBHOOK
     when:
       status: [failure]
 
@@ -3119,13 +3126,13 @@ steps:
       WORKSPACE_DIR: /tmp/build-darwin-amd64-fips
       TELEPORT_DIR: /tmp/build-darwin-amd64-fips/go/src/github.com/gravitational/teleport
       GODL_DIR: /tmp/build-darwin-amd64-fips/go/src/github.com/gravitational/godl
-      GODL_COMMIT: dev.boringcrypto.go1.15
+      BORINGCRYPTO_BRANCH: dev.boringcrypto.go1.15
     commands:
       - set -u
       - mkdir -p $TELEPORT_DIR $GODL_DIR
       - cd $GODL_DIR
       - git clone https://github.com/gravitational/godl.git .
-      - git checkout $GODL_COMMIT
+      - git checkout $BORINGCRYPTO_BRANCH
       - cd $TELEPORT_DIR
       - git clone https://github.com/gravitational/${DRONE_REPO_NAME}.git .
       - git checkout ${DRONE_TAG:-$DRONE_COMMIT}
@@ -3142,15 +3149,18 @@ steps:
       - mkdir -p $WORKSPACE_DIR/go/artifacts $WORKSPACE_DIR/go/cache
       - echo "${DRONE_TAG##v}" > $WORKSPACE_DIR/go/.version.txt
       - cat $WORKSPACE_DIR/go/.version.txt
+      - echo "${BORINGCRYPTO_BRANCH}" > $WORKSPACE_DIR/go/.bc_commit.txt
+      - cat $WORKSPACE_DIR/go/.bc_commit.txt
 
   - name: Build the boringcrypto Go builder
     environment:
+      WORKSPACE_DIR: /tmp/build-darwin-amd64-fips
       GODL_DIR: /tmp/build-darwin-amd64-fips/go/src/github.com/gravitational/godl
-      BORINGCRYPTO_BRANCH: dev.boringcrypto.go1.15
     commands:
       - set -u
       - cd $GODL_DIR
       - mkdir build
+      - export BORINGCRYPTO_BRANCH=$(cat $WORKSPACE_DIR/go/.bc_commit.txt)
       - go build -o $GODL_DIR/build/$BORINGCRYPTO_BRANCH $BORINGCRYPTO_BRANCH/main.go
 
   - name: Pull boringcrypto build tarball from S3
@@ -3162,10 +3172,11 @@ steps:
       AWS_SECRET_ACCESS_KEY:
         from_secret: AWS_SECRET_ACCESS_KEY
       AWS_REGION: us-west-2
-      BORINGCRYPTO_BRANCH: dev.boringcrypto.go1.15
+      WORKSPACE_DIR: /tmp/build-darwin-amd64-fips
       GODL_DIR: /tmp/build-darwin-amd64-fips/go/src/github.com/gravitational/godl
     commands:
       - set -u
+      - export BORINGCRYPTO_BRANCH=$(cat $WORKSPACE_DIR/go/.bc_commit.txt)
       - mkdir -p $HOME/sdk/dev.boringcrypto.go1.15
       - cd $HOME/sdk/dev.boringcrypto.go1.15
       - aws s3 cp s3://$AWS_S3_BUCKET/ci/go/$BORINGCRYPTO_BRANCH-darwin-amd64.tar.gz .
@@ -3177,7 +3188,7 @@ steps:
       GOPATH: /tmp/build-darwin-amd64-fips/go
       GOCACHE: /tmp/build-darwin-amd64-fips/go/cache
       # use custom Go compiler
-      GO_BINARY: /tmp/build-darwin-amd64-fips/go/src/github.com/gravitational/godl/build/dev.boringcrypto.go1.15
+      GODL_DIR: /tmp/build-darwin-amd64-fips/go/src/github.com/gravitational/godl
       OS: darwin
       ARCH: amd64
       WORKSPACE_DIR: /tmp/build-darwin-amd64-fips
@@ -3185,7 +3196,9 @@ steps:
     commands:
       - set -u
       - cd $WORKSPACE_DIR/go/src/github.com/gravitational/teleport
-      - make clean release OS=$OS ARCH=$ARCH FIPS=$FIPS GO_BINARY=$GO_BINARY
+      - export VERSION=$(cat $WORKSPACE_DIR/go/.version.txt)
+      - export BORINGCRYPTO_BRANCH=$(cat $WORKSPACE_DIR/go/.bc_commit.txt)
+      - make -C e clean release VERSION=$VERSION OS=$OS ARCH=$ARCH FIPS=$FIPS GO_BINARY="$GODL_DIR/build/$BORINGCRYPTO_BRANCH"
 
   - name: Copy Mac artifacts
     environment:
@@ -3312,11 +3325,12 @@ steps:
       OSS_TARBALL_PATH: /tmp/build-darwin-amd64-fips-pkg/go/artifacts
       ENT_TARBALL_PATH: /tmp/build-darwin-amd64-fips-pkg/go/artifacts
       WORKSPACE_DIR: /tmp/build-darwin-amd64-fips-pkg
+      RUNTIME: "fips"
     commands:
       - set -u
       - cd $WORKSPACE_DIR/go/src/github.com/gravitational/teleport
       - export VERSION=$(cat $WORKSPACE_DIR/go/.version.txt)
-      - make pkg OS=$OS ARCH=$ARCH
+      - make -C e pkg VERSION=$VERSION OS=$OS ARCH=$ARCH RUNTIME=$RUNTIME
 
   - name: Copy Mac pkg artifacts
     environment:
@@ -3626,6 +3640,150 @@ steps:
   - name: Clean up exec runner storage
     environment:
       WORKSPACE_DIR: /tmp/build-darwin-amd64-pkg-tsh
+    commands:
+      - set -u
+      - chmod -R u+rw $WORKSPACE_DIR
+      - rm -rf $WORKSPACE_DIR/go $WORKSPACE_DIR/.ssh
+
+---
+kind: pipeline
+type: exec
+name: build-darwin-amd64-fips-pkg-tsh
+
+concurrency:
+  limit: 1
+
+platform:
+  os: darwin
+  arch: amd64
+
+trigger:
+  event:
+    - tag
+  ref:
+    include:
+      - refs/tags/v*
+  repo:
+    include:
+      - gravitational/*
+
+depends_on:
+  - build-darwin-amd64-fips
+
+workspace:
+  path: /tmp/build-darwin-amd64-fips-pkg-tsh
+
+clone:
+  disable: true
+
+steps:
+  - name: Set up exec runner storage
+    environment:
+      WORKSPACE_DIR: /tmp/build-darwin-amd64-fips-pkg-tsh
+    commands:
+      - set -u
+      - mkdir -p $WORKSPACE_DIR
+      - chmod -R u+rw $WORKSPACE_DIR
+      - rm -rf $WORKSPACE_DIR/go $WORKSPACE_DIR/.ssh
+
+  - name: Check out code
+    environment:
+      GITHUB_PRIVATE_KEY:
+        from_secret: GITHUB_PRIVATE_KEY
+      WORKSPACE_DIR: /tmp/build-darwin-amd64-fips-pkg-tsh
+    commands:
+      - set -u
+      - mkdir -p $WORKSPACE_DIR/go/src/github.com/gravitational/teleport
+      - cd $WORKSPACE_DIR/go/src/github.com/gravitational/teleport
+      - git clone https://github.com/gravitational/${DRONE_REPO_NAME}.git .
+      - git checkout ${DRONE_TAG:-$DRONE_COMMIT}
+      # fetch enterprise submodules
+      # suppressing the newline on the end of the private key makes git operations fail on MacOS
+      # with an error like 'Load key "/path/.ssh/id_rsa": invalid format'
+      - mkdir -m 0700 $WORKSPACE_DIR/.ssh && echo "$GITHUB_PRIVATE_KEY" > $WORKSPACE_DIR/.ssh/id_rsa && chmod 600 $WORKSPACE_DIR/.ssh/id_rsa
+      - ssh-keyscan -H github.com > $WORKSPACE_DIR/.ssh/known_hosts 2>/dev/null
+      - chmod 600 $WORKSPACE_DIR/.ssh/known_hosts
+      - GIT_SSH_COMMAND='ssh -i $WORKSPACE_DIR/.ssh/id_rsa -o UserKnownHostsFile=$WORKSPACE_DIR/.ssh/known_hosts -F /dev/null' git submodule update --init e
+      # this is allowed to fail because pre-4.3 Teleport versions don't use the webassets submodule
+      - GIT_SSH_COMMAND='ssh -i $WORKSPACE_DIR/.ssh/id_rsa -o UserKnownHostsFile=$WORKSPACE_DIR/.ssh/known_hosts -F /dev/null' git submodule update --init --recursive webassets || true
+      - rm -rf $WORKSPACE_DIR/.ssh
+      - mkdir -p $WORKSPACE_DIR/go/artifacts $WORKSPACE_DIR/go/cache
+      - echo "${DRONE_TAG##v}" > $WORKSPACE_DIR/go/.version.txt
+      - cat $WORKSPACE_DIR/go/.version.txt
+
+  - name: Download built tarball artifact from S3
+    environment:
+      AWS_S3_BUCKET:
+        from_secret: AWS_S3_BUCKET
+      AWS_ACCESS_KEY_ID:
+        from_secret: AWS_ACCESS_KEY_ID
+      AWS_SECRET_ACCESS_KEY:
+        from_secret: AWS_SECRET_ACCESS_KEY
+      AWS_REGION: us-west-2
+      WORKSPACE_DIR: /tmp/build-darwin-amd64-fips-pkg-tsh
+    commands:
+      - set -u
+      - export VERSION=$(cat $WORKSPACE_DIR/go/.version.txt)
+      - export S3_PATH="tag/$${DRONE_TAG##v}/"
+      - aws s3 cp s3://$AWS_S3_BUCKET/teleport/$${S3_PATH}teleport-v$${VERSION}-darwin-amd64-fips-bin.tar.gz $WORKSPACE_DIR/go/artifacts/
+
+  - name: Build Mac tsh pkg release artifacts
+    environment:
+      OS: darwin
+      ARCH: amd64
+      APPLE_USERNAME:
+        from_secret: APPLE_USERNAME
+      APPLE_PASSWORD:
+        from_secret: APPLE_PASSWORD
+      BUILDBOX_PASSWORD:
+        from_secret: BUILDBOX_PASSWORD
+      OSS_TARBALL_PATH: /tmp/build-darwin-amd64-fips-pkg-tsh/go/artifacts
+      WORKSPACE_DIR: /tmp/build-darwin-amd64-fips-pkg-tsh
+      RUNTIME: "fips"
+    commands:
+      - set -u
+      - cd $WORKSPACE_DIR/go/src/github.com/gravitational/teleport
+      - export VERSION=$(cat $WORKSPACE_DIR/go/.version.txt)
+      # set HOME explicitly (as Drone overrides it normally)
+      - export HOME=/Users/build
+      # unlock login keychain
+      - security unlock-keychain -p $${BUILDBOX_PASSWORD} login.keychain
+      # show available certificates
+      - security find-identity -v
+      # build pkg
+      - make pkg-tsh VERSION=$VERSION OS=$OS ARCH=$ARCH RUNTIME=$RUNTIME
+
+  - name: Copy Mac tsh pkg artifacts
+    environment:
+      WORKSPACE_DIR: /tmp/build-darwin-amd64-fips-pkg-tsh
+    commands:
+      - set -u
+      - cd $WORKSPACE_DIR/go/src/github.com/gravitational/teleport
+      # delete temporary tarball artifacts so we don't re-upload them in the next stage
+      - rm -rf $WORKSPACE_DIR/go/artifacts/*.tar.gz
+      # copy release archives to artifact directory
+      - cp build/tsh*.pkg $WORKSPACE_DIR/go/artifacts
+      # generate checksums (for mac)
+      - cd $WORKSPACE_DIR/go/artifacts && for FILE in tsh*.pkg; do shasum -a 256 $FILE > $FILE.sha256; done && ls -l
+
+  - name: Upload to S3
+    environment:
+      AWS_S3_BUCKET:
+        from_secret: AWS_S3_BUCKET
+      AWS_ACCESS_KEY_ID:
+        from_secret: AWS_ACCESS_KEY_ID
+      AWS_SECRET_ACCESS_KEY:
+        from_secret: AWS_SECRET_ACCESS_KEY
+      AWS_REGION: us-west-2
+      WORKSPACE_DIR: /tmp/build-darwin-amd64-fips-pkg-tsh
+    commands:
+      - set -u
+      - cd $WORKSPACE_DIR/go/artifacts
+      - aws s3 sync . s3://$AWS_S3_BUCKET/teleport/tag/${DRONE_TAG##v}
+
+  - name: Clean up exec runner storage
+    environment:
+      WORKSPACE_DIR: /tmp/build-darwin-amd64-fips-pkg-tsh
     commands:
       - set -u
       - chmod -R u+rw $WORKSPACE_DIR
@@ -4810,6 +4968,6 @@ volumes:
 
 ---
 kind: signature
-hmac: f5ccd1c8489a5c5ed2b663af6ef88928119438cdfdad882ec0fccd8f01a9bd4b
+hmac: 239293877a8d8b716ac474df0fa9cdd0c3b0a00ddd3fd8373f576d4e44f7870b
 
 ...
